name: ROS 2 CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/ros2_ws/**'
      - '.github/workflows/ros2.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/ros2_ws/**'
      - '.github/workflows/ros2.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    
    strategy:
      matrix:
        ros_distro: [humble]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test ROS 2 workspace
      uses: ros-tooling/action-ros-ci@v0.4
      with:
        package-name: spacecraft_msgs autonomy_manager state_estimator ground_link
        target-ros2-distro: ${{ matrix.ros_distro }}
        vcs-repo-file-url: |
          https://raw.githubusercontent.com/ros2/ros2/${{ matrix.ros_distro }}/ros2.repos
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc", "coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/main/index.yaml
        
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      with:
        files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
        flags: ros2
        name: ros2-coverage
